What is Pandas?
pandas is an open-source data analysis and manipulation library for Python. It provides data structures like Series and DataFrame that make it easy to work with structured data, perform data cleaning, transformation, and analysis.

In [49]:
import pandas as pd
import numpy as np
import warnings 
import seaborn as sns
warnings.filterwarnings("ignore")

## 1.	Create a DataFrame

In [50]:
# Q Create a DataFrame containing student names, roll numbers, branch, and marks.
student_data = {
    'Student Name': ['Aarav', 'Ananya', 'Diya', 'Ishaan', 'Kabir', 'Meera', 'Rahul', 'Riya',  'Arjun', 'Saanvi'],
    'Roll Number': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Branch': ['CSE', 'ECE', 'ME', 'CSE', 'IT', 'CE', 'CSE', 'ECE', 'IT', 'ME'],
    'Marks': [85, 92, 78, 65, 88, 74, 91, 83, 79, 81]
}

df = pd.DataFrame(student_data)

In [51]:
# Q Display the first 5 and last 5 records.
print(df.head())
print(df.tail())

  Student Name  Roll Number Branch  Marks
0        Aarav          101    CSE     85
1       Ananya          102    ECE     92
2         Diya          103     ME     78
3       Ishaan          104    CSE     65
4        Kabir          105     IT     88
  Student Name  Roll Number Branch  Marks
5        Meera          106     CE     74
6        Rahul          107    CSE     91
7         Riya          108    ECE     83
8        Arjun          109     IT     79
9       Saanvi          110     ME     81

## 2.	Series Operations

In [52]:
# Q o	Create a Pandas Series containing marks of 10 students.
marks = student_data["Marks"]
Sname = student_data['Student Name']
S = pd.Series(marks , index= Sname , name = "student_name")
S

Aarav     85
Ananya    92
Diya      78
Ishaan    65
Kabir     88
Meera     74
Rahul     91
Riya      83
Arjun     79
Saanvi    81
Name: student_name, dtype: int64

In [53]:
print("Max : ", S.max())
print("Min : ",S.min())
print("Mean : ",S.mean())
print("Median : ",S.median())

Max :  92
Min :  65
Mean :  81.6
Median :  82.0

## 3.	DataFrame Information

In [54]:
employee_data = {
    'Employee ID':[101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Amit', 'Priya', 'Vikram', 'Neha', 'Rohan', 'Sneha', 'Aditya', 'Pooja'],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing', 'Finance', 'HR', 'IT'],
    'Salary': [85000, 60000, 95000, 87000, 55000, 92000, 62000, 89000]
}
df_e = pd.DataFrame(employee_data)

In [55]:

# o	Display its shape, columns, data types, and statistical summary.
df_e["Salary"].describe()

count        8.000000
mean     78125.000000
std      16234.333107
min      55000.000000
25%      61500.000000
50%      86000.000000
75%      89750.000000
max      95000.000000
Name: Salary, dtype: float64

## 4.	Selecting Columns

In [56]:
# o	Given a student DataFrame, select only Name, Branch, and Marks columns.
df[["Student Name" , "Branch" , "Marks"]].head()

  Student Name Branch  Marks
0        Aarav    CSE     85
1       Ananya    ECE     92
2         Diya     ME     78
3       Ishaan    CSE     65
4        Kabir     IT     88

## 5.	Selecting Rows

In [57]:
df.iloc[5:16]

  Student Name  Roll Number Branch  Marks
5        Meera          106     CE     74
6        Rahul          107    CSE     91
7         Riya          108    ECE     83
8        Arjun          109     IT     79
9       Saanvi          110     ME     81

## 6.	Using loc

In [58]:
## o	Set the student roll number as the index.
# df["Roll Number"]
df.set_index(keys="Roll Number", inplace=True)

In [59]:
# o	Select students with specific roll numbers using loc.
df.loc[[102,105]]

            Student Name Branch  Marks
Roll Number
102               Ananya    ECE     92
105                Kabir     IT     88

## 7.	Filtering Data

In [60]:
#o	Find all students who scored more than 75 marks.
df[df["Marks"] >= 75]

            Student Name Branch  Marks
Roll Number
101                Aarav    CSE     85
102               Ananya    ECE     92
103                 Diya     ME     78
105                Kabir     IT     88
107                Rahul    CSE     91
108                 Riya    ECE     83
109                Arjun     IT     79
110               Saanvi     ME     81

## 8.	Multiple Conditions

In [61]:
# o	Find students from the CSE branch who scored more than 80.
df[(df["Marks"]  >= 80)  & (  df["Branch"] == "CSE")]

            Student Name Branch  Marks
Roll Number
101                Aarav    CSE     85
107                Rahul    CSE     91

## 9.	Adding a Column

In [62]:
## o	Add a Result column based on marks:
# 	Marks ≥ 40 → Pass
# 	Marks < 40 → Fail

df["Result"] = np.where(df["Marks"] >= 40, "Pass", "Fail")
df.head()

            Student Name Branch  Marks Result
Roll Number
101                Aarav    CSE     85   Pass
102               Ananya    ECE     92   Pass
103                 Diya     ME     78   Pass
104               Ishaan    CSE     65   Pass
105                Kabir     IT     88   Pass

## 10.	Sorting Data

In [63]:
## o	Sort students by marks in descending order.
df_top = df.sort_values(by = "Marks" ,ascending = False)
df_top

            Student Name Branch  Marks Result
Roll Number
102               Ananya    ECE     92   Pass
107                Rahul    CSE     91   Pass
105                Kabir     IT     88   Pass
101                Aarav    CSE     85   Pass
108                 Riya    ECE     83   Pass
110               Saanvi     ME     81   Pass
109                Arjun     IT     79   Pass
103                 Diya     ME     78   Pass
106                Meera     CE     74   Pass
104               Ishaan    CSE     65   Pass

In [64]:
## o	Display the top 5 students.
df_top.head()

            Student Name Branch  Marks Result
Roll Number
102               Ananya    ECE     92   Pass
107                Rahul    CSE     91   Pass
105                Kabir     IT     88   Pass
101                Aarav    CSE     85   Pass
108                 Riya    ECE     83   Pass

In [65]:
df

            Student Name Branch  Marks Result
Roll Number
101                Aarav    CSE     85   Pass
102               Ananya    ECE     92   Pass
103                 Diya     ME     78   Pass
104               Ishaan    CSE     65   Pass
105                Kabir     IT     88   Pass
106                Meera     CE     74   Pass
107                Rahul    CSE     91   Pass
108                 Riya    ECE     83   Pass
109                Arjun     IT     79   Pass
110               Saanvi     ME     81   Pass

## 11.	Missing Values

In [66]:
data = {
    "Roll Number":[101, 102, np.nan, 104, 105, 106, np.nan, 108, 109, 110],
    "Student Name":["Aarav", "Ananya", "Diya", np.nan, "Kabir", "Meera", "Rahul", "Riya", np.nan, "Saanvi"],
    "Branch":["CSE", np.nan, "ME", "CSE", "IT", "CE", np.nan, "ECE", "IT", "ME"],
    "Marks":[85, np.nan, 78, 65, 88, np.nan, 91, 83, 79, 81],}

df_m = pd.DataFrame(data)

In [67]:
# o	Identify missing values using isnull() and isna().
df_m.isna().sum()

Roll Number     2
Student Name    2
Branch          2
Marks           2
dtype: int64

## 12.	Handling Missing Values

In [68]:
df_m['Marks'] = df_m['Marks'].fillna(df_m['Marks'].mean())
df_m

   Roll Number Student Name Branch  Marks
0        101.0        Aarav    CSE  85.00
1        102.0       Ananya    NaN  81.25
2          NaN         Diya     ME  78.00
3        104.0          NaN    CSE  65.00
4        105.0        Kabir     IT  88.00
5        106.0        Meera     CE  81.25
6          NaN        Rahul    NaN  91.00
7        108.0         Riya    ECE  83.00
8        109.0          NaN     IT  79.00
9        110.0       Saanvi     ME  81.00

## 13.	Removing Duplicates

In [69]:
dup = pd.DataFrame({
    'Roll_No': [101, 102, 101, 103],
    'Name': ['Rahul', 'Priya', 'Rahul', 'Amit'],
    'Marks': [85, 92, 85, 78]
})
dup

   Roll_No   Name  Marks
0      101  Rahul     85
1      102  Priya     92
2      101  Rahul     85
3      103   Amit     78

In [70]:
dup.drop_duplicates()

   Roll_No   Name  Marks
0      101  Rahul     85
1      102  Priya     92
3      103   Amit     78

## 14.	Rename Columns

In [71]:
# o	Rename Student_Name to Name and Student_Marks to Marks.
df_students = df.reset_index().rename(columns={
    "Student Name": "Student_Name",
    "Marks": "Student_Marks"
})

df_renamed = df_students.rename(columns={
    "Student_Name": "Name",
    "Student_Marks": "Marks"
})

df_renamed.head()

   Roll Number    Name Branch  Marks Result
0          101   Aarav    CSE     85   Pass
1          102  Ananya    ECE     92   Pass
2          103    Diya     ME     78   Pass
3          104  Ishaan    CSE     65   Pass
4          105   Kabir     IT     88   Pass

## 15. Export and Import

In [72]:
# Save dataframe into csv and read it again.
df.to_csv("students.csv")

new_df = pd.read_csv("students.csv")
new_df.head()

   Roll Number Student Name Branch  Marks Result
0          101        Aarav    CSE     85   Pass
1          102       Ananya    ECE     92   Pass
2          103         Diya     ME     78   Pass
3          104       Ishaan    CSE     65   Pass
4          105        Kabir     IT     88   Pass

## 16. GroupBy - Average Marks

In [73]:
# Average marks branch wise.
df.groupby("Branch")["Marks"].mean()

Branch
CE     74.000000
CSE    80.333333
ECE    87.500000
IT     83.500000
ME     79.500000
Name: Marks, dtype: float64

## 17. GroupBy - Multiple Aggregations

In [74]:
# Min, max, mean and std branch wise.
df.groupby("Branch")["Marks"].agg(["min", "max", "mean", "std"])

        min  max       mean        std
Branch
CE       74   74  74.000000        NaN
CSE      65   91  80.333333  13.613719
ECE      83   92  87.500000   6.363961
IT       79   88  83.500000   6.363961
ME       78   81  79.500000   2.121320

## 18. Value Counts

In [75]:
# Count students in each branch.
df["Branch"].value_counts()

Branch
CSE    3
ECE    2
ME     2
IT     2
CE     1
Name: count, dtype: int64

## 19. Conditional Column

In [76]:
# Make grade column.
def grade(m):
    if m >= 90:
        return "A"
    elif m >= 75:
        return "B"
    elif m >= 60:
        return "C"
    elif m >= 40:
        return "D"
    else:
        return "F"

df1 = df.copy()
df1["Grade"] = df1["Marks"].apply(grade)
df1

            Student Name Branch  Marks Result Grade
Roll Number
101                Aarav    CSE     85   Pass     B
102               Ananya    ECE     92   Pass     A
103                 Diya     ME     78   Pass     B
104               Ishaan    CSE     65   Pass     C
105                Kabir     IT     88   Pass     B
106                Meera     CE     74   Pass     C
107                Rahul    CSE     91   Pass     A
108                 Riya    ECE     83   Pass     B
109                Arjun     IT     79   Pass     B
110               Saanvi     ME     81   Pass     B

## 20. Apply Function

In [77]:
# Percentage out of 500.
data = {"Name": ["Aarav", "Ananya", "Diya"], "Marks": [420, 455, 380]}
per = pd.DataFrame(data)

per["Percentage"] = per["Marks"].apply(lambda x: x / 500 * 100)
per

     Name  Marks  Percentage
0   Aarav    420        84.0
1  Ananya    455        91.0
2    Diya    380        76.0

## 21. String Operations

In [78]:
# Uppercase name and first letter.
names = pd.DataFrame({"Name": ["aarav", "ananya", "diya", "kabir"]})

names["Upper_Name"] = names["Name"].str.upper()
names["First_Letter"] = names["Name"].str[0]
names

     Name Upper_Name First_Letter
0   aarav      AARAV            a
1  ananya     ANANYA            a
2    diya       DIYA            d
3   kabir      KABIR            k

## 22. DateTime Operations

In [79]:
# Extract year, month and day from joining date.
emp = pd.DataFrame({
    "Name": ["Amit", "Priya", "Neha"],
    "Joining_Date": ["2020-01-15", "2021-05-20", "2022-09-10"]
})

emp["Joining_Date"] = pd.to_datetime(emp["Joining_Date"])
emp["Year"] = emp["Joining_Date"].dt.year
emp["Month"] = emp["Joining_Date"].dt.month
emp["Day"] = emp["Joining_Date"].dt.day
emp

    Name Joining_Date  Year  Month  Day
0   Amit   2020-01-15  2020      1   15
1  Priya   2021-05-20  2021      5   20
2   Neha   2022-09-10  2022      9   10

## 23. Filtering with query()

In [80]:
# Salary greater than 50000 and experience greater than 5.
emp = pd.DataFrame({
    "Name": ["Amit", "Priya", "Neha", "Rohan"],
    "Salary": [45000, 65000, 72000, 48000],
    "Experience": [4, 7, 8, 6]
})

emp.query("Salary > 50000 and Experience > 5")

    Name  Salary  Experience
1  Priya   65000           7
2   Neha   72000           8

## 24. Duplicate Analysis

In [81]:
# Duplicate email and keep latest record.
data = {
    "Email": ["a@gmail.com", "b@gmail.com", "a@gmail.com", "c@gmail.com"],
    "Name": ["Amit", "Priya", "Amit New", "Neha"],
    "Date": ["2024-01-01", "2024-01-02", "2024-02-01", "2024-01-10"]
}
email = pd.DataFrame(data)
email["Date"] = pd.to_datetime(email["Date"])

email.sort_values("Date").drop_duplicates("Email", keep="last")

         Email      Name       Date
1  b@gmail.com     Priya 2024-01-02
3  c@gmail.com      Neha 2024-01-10
2  a@gmail.com  Amit New 2024-02-01

## 25. Merge DataFrames

In [82]:
# Merge student info and result.
stu = pd.DataFrame({"Student_ID": [1, 2, 3], "Name": ["Aarav", "Ananya", "Diya"]})
res = pd.DataFrame({"Student_ID": [1, 2, 3], "Marks": [85, 92, 78]})

pd.merge(stu, res, on="Student_ID")

   Student_ID    Name  Marks
0           1   Aarav     85
1           2  Ananya     92
2           3    Diya     78

## 26. Join DataFrames

In [83]:
# Different joins.
a = pd.DataFrame({"ID": [1, 2, 3], "Name": ["A", "B", "C"]})
b = pd.DataFrame({"ID": [2, 3, 4], "Marks": [80, 90, 70]})

inner = pd.merge(a, b, on="ID", how="inner")
left = pd.merge(a, b, on="ID", how="left")
right = pd.merge(a, b, on="ID", how="right")
outer = pd.merge(a, b, on="ID", how="outer")

print(inner)
print(left)
print(right)
print(outer)

   ID Name  Marks
0   2    B     80
1   3    C     90
   ID Name  Marks
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0
   ID Name  Marks
0   2    B     80
1   3    C     90
2   4  NaN     70
   ID Name  Marks
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0
3   4  NaN   70.0

## 27. Concatenation

In [84]:
# Combine semester data.
sem1 = pd.DataFrame({"Name": ["Aarav", "Ananya"], "Sem": [1, 1]})
sem2 = pd.DataFrame({"Name": ["Diya", "Kabir"], "Sem": [2, 2]})

pd.concat([sem1, sem2], ignore_index=True)

     Name  Sem
0   Aarav    1
1  Ananya    1
2    Diya    2
3   Kabir    2

## 28. Pivot Table

In [85]:
# Total sales by region and product.
sales = pd.DataFrame({
    "Region": ["North", "North", "South", "South"],
    "Product": ["Laptop", "Mobile", "Laptop", "Mobile"],
    "Sales": [50000, 30000, 60000, 25000]
})

pd.pivot_table(sales, values="Sales", index="Region", columns="Product", aggfunc="sum")

Product  Laptop  Mobile
Region
North     50000   30000
South     60000   25000

## 29. Ranking

In [86]:
# Rank by marks.
df2 = df.copy()
df2["Rank"] = df2["Marks"].rank(ascending=False).astype(int)
df2.sort_values("Rank")

            Student Name Branch  Marks Result  Rank
Roll Number
102               Ananya    ECE     92   Pass     1
107                Rahul    CSE     91   Pass     2
105                Kabir     IT     88   Pass     3
101                Aarav    CSE     85   Pass     4
108                 Riya    ECE     83   Pass     5
110               Saanvi     ME     81   Pass     6
109                Arjun     IT     79   Pass     7
103                 Diya     ME     78   Pass     8
106                Meera     CE     74   Pass     9
104               Ishaan    CSE     65   Pass    10

## 30. Top-N Analysis

In [87]:
# Top 3 students from each branch.
data = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "Branch": ["CSE", "CSE", "CSE", "CSE", "IT", "IT", "IT", "IT"],
    "Marks": [90, 80, 75, 60, 88, 82, 70, 65]
})

data.sort_values("Marks", ascending=False).groupby("Branch").head(3)

  Name Branch  Marks
0    A    CSE     90
4    E     IT     88
5    F     IT     82
1    B    CSE     80
2    C    CSE     75
6    G     IT     70

## 31. Group-Based Filtering

In [88]:
# Branches where average marks greater than 70.
avg = df.groupby("Branch")["Marks"].mean()
avg[avg > 70]

Branch
CE     74.000000
CSE    80.333333
ECE    87.500000
IT     83.500000
ME     79.500000
Name: Marks, dtype: float64

## 32. Cumulative Analysis

In [89]:
# Cumulative sales.
sales = pd.DataFrame({"Month": ["Jan", "Feb", "Mar", "Apr"], "Sales": [10000, 15000, 12000, 20000]})

sales["Cumulative"] = sales["Sales"].cumsum()
sales

  Month  Sales  Cumulative
0   Jan  10000       10000
1   Feb  15000       25000
2   Mar  12000       37000
3   Apr  20000       57000

## 33. Rolling Average

In [90]:
# 3 month rolling average.
sales["Rolling_Avg"] = sales["Sales"].rolling(3).mean()
sales

  Month  Sales  Cumulative   Rolling_Avg
0   Jan  10000       10000           NaN
1   Feb  15000       25000           NaN
2   Mar  12000       37000  12333.333333
3   Apr  20000       57000  15666.666667

## 34. Frequency Analysis

In [91]:
# Top 10 products.
tran = pd.DataFrame({"Product": ["Pen", "Book", "Pen", "Bag", "Book", "Pen", "Pencil"]})

tran["Product"].value_counts().head(10)

Product
Pen       3
Book      2
Bag       1
Pencil    1
Name: count, dtype: int64

## 35. Data Cleaning

In [92]:
# Clean messy data.
messy = pd.DataFrame({
    "Name": [" aarav", "AARAV", "diya", None],
    "Branch": ["cse", "CSE", "it", "IT"],
    "Marks": ["85", "85", "90", None]
})

clean = messy.drop_duplicates().copy()
clean["Name"] = clean["Name"].str.strip().str.title()
clean["Branch"] = clean["Branch"].str.upper()
clean["Marks"] = pd.to_numeric(clean["Marks"])
clean["Marks"] = clean["Marks"].fillna(clean["Marks"].mean())
clean

    Name Branch      Marks
0  Aarav    CSE  85.000000
1  Aarav    CSE  85.000000
2   Diya     IT  90.000000
3    NaN     IT  86.666667

## 36. Student Performance Analytics

In [93]:
# Simple student performance analysis.
perf = pd.DataFrame({
    "Student_ID": [1,1,2,2,3,3,4,4],
    "Name": ["Aarav","Aarav","Diya","Diya","Kabir","Kabir","Meera","Meera"],
    "Branch": ["CSE","CSE","CSE","CSE","IT","IT","IT","IT"],
    "Subject": ["Python","SQL","Python","SQL","Python","SQL","Python","SQL"],
    "Marks": [85, 80, 35, 32, 90, 88, 55, 30],
    "Attendance": [80, 82, 70, 72, 90, 91, 74, 73]
})

subject_avg = perf.groupby("Subject")["Marks"].mean()
top3 = perf.groupby(["Branch", "Name"])["Marks"].mean().reset_index().sort_values("Marks", ascending=False).groupby("Branch").head(3)
low_att = perf[perf["Attendance"] < 75]
fail = perf[perf["Marks"] < 40].groupby("Name").size()

print(subject_avg)
print(top3)
print(low_att)
print(fail[fail > 1])

Subject
Python    66.25
SQL       57.50
Name: Marks, dtype: float64
  Branch   Name  Marks
2     IT  Kabir   89.0
0    CSE  Aarav   82.5
3     IT  Meera   42.5
1    CSE   Diya   33.5
   Student_ID   Name Branch Subject  Marks  Attendance
2           2   Diya    CSE  Python     35          70
3           2   Diya    CSE     SQL     32          72
6           4  Meera     IT  Python     55          74
7           4  Meera     IT     SQL     30          73
Name
Diya    2
dtype: int64

## 37. Multi-Level GroupBy

In [94]:
# Revenue by year, month, region and category.
ecom = pd.DataFrame({
    "Date": ["2024-01-10", "2024-01-20", "2024-02-05", "2024-02-12"],
    "Region": ["North", "South", "North", "South"],
    "Category": ["Mobile", "Laptop", "Laptop", "Mobile"],
    "Revenue": [20000, 60000, 55000, 25000]
})

ecom["Date"] = pd.to_datetime(ecom["Date"])
ecom["Year"] = ecom["Date"].dt.year
ecom["Month"] = ecom["Date"].dt.month

ecom.groupby(["Year", "Month", "Region", "Category"])["Revenue"].sum()

Year  Month  Region  Category
2024  1      North   Mobile      20000
             South   Laptop      60000
      2      North   Laptop      55000
             South   Mobile      25000
Name: Revenue, dtype: int64

## 38. Advanced Sales Analysis

In [95]:
# Monthly revenue and growth.
txn = pd.DataFrame({
    "Date": ["2024-01-05", "2024-02-05", "2024-03-05", "2024-03-10"],
    "Customer": ["A", "A", "B", "C"],
    "Revenue": [1000, 1500, 3000, 2000]
})

txn["Date"] = pd.to_datetime(txn["Date"])
txn["Month"] = txn["Date"].dt.to_period("M")
month_rev = txn.groupby("Month")["Revenue"].sum().reset_index()
month_rev["Growth"] = month_rev["Revenue"].pct_change() * 100
month_rev

     Month  Revenue      Growth
0  2024-01     1000         NaN
1  2024-02     1500   50.000000
2  2024-03     5000  233.333333

## 39. Customer Segmentation

In [96]:
# RFM table.
data = pd.DataFrame({
    "Customer": ["A", "A", "B", "C", "C"],
    "Date": ["2024-01-10", "2024-03-10", "2024-02-05", "2024-01-20", "2024-03-15"],
    "Amount": [1000, 1500, 800, 500, 700]
})

data["Date"] = pd.to_datetime(data["Date"])
today = data["Date"].max()
rfm = data.groupby("Customer").agg(
    Recency=("Date", lambda x: (today - x.max()).days),
    Frequency=("Customer", "count"),
    Monetary=("Amount", "sum")
)
rfm

          Recency  Frequency  Monetary
Customer
A               5          2      2500
B              39          1       800
C               0          2      1200

## 40. Time-Series Analysis

In [97]:
# Monthly revenue and 7 day rolling average.
ts = pd.DataFrame({
    "Date": pd.date_range("2024-01-01", periods=20),
    "Sales": [100,120,130,90,160,180,200,210,190,220,230,250,240,260,270,300,280,310,320,330]
})

ts["Date"] = pd.to_datetime(ts["Date"])
ts = ts.set_index("Date")
ts["Rolling_7"] = ts["Sales"].rolling(7).mean()
monthly = ts.resample("ME")["Sales"].sum()

print(monthly)
ts.head(10)

Date
2024-01-31    4390
Freq: ME, Name: Sales, dtype: int64

            Sales   Rolling_7
Date
2024-01-01    100         NaN
2024-01-02    120         NaN
2024-01-03    130         NaN
2024-01-04     90         NaN
2024-01-05    160         NaN
2024-01-06    180         NaN
2024-01-07    200  140.000000
2024-01-08    210  155.714286
2024-01-09    190  165.714286
2024-01-10    220  178.571429

## 41. Advanced Merge

In [98]:
# Merge customer, order and product table.
cust = pd.DataFrame({"Customer_ID": [1,2], "Name": ["Amit", "Priya"]})
order = pd.DataFrame({"Order_ID": [101,102], "Customer_ID": [1,2], "Product_ID": [11,12], "Qty": [2,1]})
prod = pd.DataFrame({"Product_ID": [11,12], "Product": ["Pen", "Book"], "Price": [10,100]})

final = order.merge(cust, on="Customer_ID").merge(prod, on="Product_ID")
final["Revenue"] = final["Qty"] * final["Price"]
final

   Order_ID  Customer_ID  Product_ID  Qty   Name Product  Price  Revenue
0       101            1          11    2   Amit     Pen     10       20
1       102            2          12    1  Priya    Book    100      100

## 42. Missing Data Strategy

In [99]:
# Fill missing values branch wise.
data = pd.DataFrame({
    "Branch": ["CSE", "CSE", "IT", "IT"],
    "Marks": [80, None, 90, None],
    "City": ["Delhi", None, "Pune", None]
})

print(data.isnull().mean() * 100)

data["Marks"] = data.groupby("Branch")["Marks"].transform(lambda x: x.fillna(x.median()))
data["City"] = data.groupby("Branch")["City"].transform(lambda x: x.fillna(x.mode()[0]))
data

Branch     0.0
Marks     50.0
City      50.0
dtype: float64

  Branch  Marks   City
0    CSE   80.0  Delhi
1    CSE   80.0  Delhi
2     IT   90.0   Pune
3     IT   90.0   Pune

## 43. Window-Based Analysis

In [100]:
# Previous salary and growth.
sal = pd.DataFrame({
    "Name": ["Amit", "Amit", "Priya", "Priya"],
    "Year": [2023, 2024, 2023, 2024],
    "Salary": [40000, 50000, 60000, 66000]
})

sal["Previous"] = sal.groupby("Name")["Salary"].shift(1)
sal["Growth"] = (sal["Salary"] - sal["Previous"]) / sal["Previous"] * 100
sal[sal["Growth"] > 20]

   Name  Year  Salary  Previous  Growth
1  Amit  2024   50000   40000.0    25.0

## 44. Advanced Ranking

In [101]:
# Total, average and rank branch wise.
score = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Branch": ["CSE", "CSE", "IT", "IT"],
    "Python": [80, 90, 70, 95],
    "SQL": [85, 88, 75, 92]
})

score["Total"] = score["Python"] + score["SQL"]
score["Average"] = score[["Python", "SQL"]].mean(axis=1)
score["Rank"] = score.groupby("Branch")["Total"].rank(ascending=False).astype(int)
score

  Name Branch  Python  SQL  Total  Average  Rank
0    A    CSE      80   85    165     82.5     2
1    B    CSE      90   88    178     89.0     1
2    C     IT      70   75    145     72.5     2
3    D     IT      95   92    187     93.5     1

## 45. Cohort Analysis

In [102]:
# Simple cohort table.
buy = pd.DataFrame({
    "Customer": ["A", "A", "B", "C", "C"],
    "Date": ["2024-01-10", "2024-02-10", "2024-01-20", "2024-02-05", "2024-03-05"]
})

buy["Date"] = pd.to_datetime(buy["Date"])
buy["Month"] = buy["Date"].dt.to_period("M")
buy["Cohort"] = buy.groupby("Customer")["Month"].transform("min")

buy.groupby(["Cohort", "Month"])["Customer"].nunique()

Cohort   Month
2024-01  2024-01    2
         2024-02    1
2024-02  2024-02    1
         2024-03    1
Name: Customer, dtype: int64

## 46. Fraud Detection with Pandas

In [103]:
# Find high amount and quick transactions.
bank = pd.DataFrame({
    "Account": ["A", "A", "A", "B", "B"],
    "Time": pd.to_datetime(["2024-01-01 10:00", "2024-01-01 10:03", "2024-01-02 11:00", "2024-01-01 09:00", "2024-01-01 09:04"]),
    "Amount": [500, 600, 5000, 700, 750]
})

bank["Avg"] = bank.groupby("Account")["Amount"].transform("mean")
high = bank[bank["Amount"] > bank["Avg"] * 2]
bank["Diff"] = bank.groupby("Account")["Time"].diff().dt.total_seconds() / 60
quick = bank[bank["Diff"] <= 5]

print(high)
quick

  Account                Time  Amount          Avg
2       A 2024-01-02 11:00:00    5000  2033.333333

  Account                Time  Amount          Avg  Diff
1       A 2024-01-01 10:03:00     600  2033.333333   3.0
4       B 2024-01-01 09:04:00     750   725.000000   4.0

## 47. Inventory Management

In [104]:
# Stock and reorder level.
inv = pd.DataFrame({
    "Product": ["Pen", "Book", "Bag"],
    "Opening": [100, 50, 30],
    "Purchase": [50, 20, 10],
    "Sold": [120, 30, 35],
    "Reorder": [40, 25, 10]
})

inv["Current_Stock"] = inv["Opening"] + inv["Purchase"] - inv["Sold"]
inv["Turnover"] = inv["Sold"] / inv["Opening"]
inv[inv["Current_Stock"] < inv["Reorder"]]

  Product  Opening  Purchase  Sold  Reorder  Current_Stock  Turnover
0     Pen      100        50   120       40             30  1.200000
2     Bag       30        10    35       10              5  1.166667

## 48. Large Dataset Optimization

In [105]:
# Memory before and after datatype change.
big = pd.DataFrame({
    "Branch": ["CSE", "IT", "CSE", "ECE"] * 1000,
    "Marks": [80, 90, 70, 85] * 1000
})

before = big.memory_usage(deep=True).sum()
big["Branch"] = big["Branch"].astype("category")
big["Marks"] = big["Marks"].astype("int8")
after = big.memory_usage(deep=True).sum()

print("Before:", before)
print("After:", after)

Before: 239132
After: 8287

## 49. Real-World Data Cleaning Challenge

In [106]:
# Full cleaning example.
raw = pd.DataFrame({
    "Name": [" amit ", "AMIT", "priya", None],
    "Date": ["2024-01-01", "2024-01-01", "wrong", "2024-02-01"],
    "Category": [" cse", "CSE", "it", "IT"],
    "Marks": [80, "80", 999, None]
})

clean = raw.drop_duplicates().copy()
clean["Name"] = clean["Name"].str.strip().str.title().fillna("Unknown")
clean["Category"] = clean["Category"].str.strip().str.upper()
clean["Date"] = pd.to_datetime(clean["Date"], errors="coerce")
clean["Marks"] = pd.to_numeric(clean["Marks"], errors="coerce")
clean["Marks"] = clean["Marks"].fillna(clean["Marks"].median())
clean = clean[clean["Marks"] <= 100]
clean

      Name       Date Category  Marks
0     Amit 2024-01-01      CSE   80.0
1     Amit 2024-01-01      CSE   80.0
3  Unknown 2024-02-01       IT   80.0

## 50. Capstone Pandas Project - E-Commerce Analytics

In [107]:
# Small ecommerce analysis.
customers = pd.DataFrame({"Customer_ID": [1,2,3], "Name": ["Amit", "Priya", "Neha"], "Region": ["North", "South", "North"]})
products = pd.DataFrame({"Product_ID": [11,12], "Product": ["Laptop", "Mobile"], "Price": [50000, 20000]})
orders = pd.DataFrame({
    "Order_ID": [101,102,103,104],
    "Customer_ID": [1,2,1,3],
    "Product_ID": [11,12,12,11],
    "Qty": [1,2,1,1],
    "Date": ["2024-01-10", "2024-01-20", "2024-02-05", "2024-02-15"]
})

orders["Date"] = pd.to_datetime(orders["Date"])
final = orders.merge(customers, on="Customer_ID").merge(products, on="Product_ID")
final["Revenue"] = final["Qty"] * final["Price"]
final["Month"] = final["Date"].dt.to_period("M")

monthly_sales = final.groupby("Month")["Revenue"].sum()
product_sales = final.groupby("Product")["Revenue"].sum()
region_sales = final.groupby("Region")["Revenue"].sum()
top_customer = final.groupby("Name")["Revenue"].sum().sort_values(ascending=False)

print(monthly_sales)
print(product_sales)
print(region_sales)
print(top_customer)
print("Final business insights")
print("North region has more sales.")
print("Laptop gives more revenue.")
print("Amit is top customer.")

Month
2024-01    90000
2024-02    70000
Freq: M, Name: Revenue, dtype: int64
Product
Laptop    100000
Mobile     60000
Name: Revenue, dtype: int64
Region
North    120000
South     40000
Name: Revenue, dtype: int64
Name
Amit     70000
Neha     50000
Priya    40000
Name: Revenue, dtype: int64
Final business insights
North region has more sales.
Laptop gives more revenue.
Amit is top customer.