In [1]:
import pandas as pd

In [ ]:
# Create a DataFrame
# Q-1: Create a pandas dataframe containing the following columns: Name, Roll Number, Branch, Marks.
#     : Display the first 5 and last 5 records.
student = {
    "RollNo": [101,102,103,104,105,106,107,108,109,110,
               111,112,113,114,115,116,117,118,119,120,
               121,122,123,124,125,126,127,128,129,130],

    "Name": ["Aarav","Priya","Rahul","Sneha","Karan",
             "Ananya","Vivek","Neha","Rohit","Simran",
             "Aditya","Pooja","Mohit","Riya","Arjun",
             "Kavya","Nikhil","Isha","Manish","Tanya",
             "Deepak","Meera","Saurabh","Divya","Akash",
             "Bhavna","Harsh","Nisha","Yash","Aditi"],

    "Branch": ["CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE"],

    "Marks": [85,92,78,65,88,
              95,56,72,81,69,
              91,84,38,74,90,
              77,83,58,97,62,
              48,79,86,55,93,
              41,67,82,35,89]
}

In [3]:
df = pd.DataFrame(student)
print(df)

    RollNo     Name Branch  Marks
0      101    Aarav    CSE     85
1      102    Priya   AIML     92
2      103    Rahul    ECE     78
3      104    Sneha     ME     65
4      105    Karan     CE     88
5      106   Ananya    CSE     95
6      107    Vivek   AIML     56
7      108     Neha    ECE     72
8      109    Rohit     ME     81
9      110   Simran     CE     69
10     111   Aditya    CSE     91
11     112    Pooja   AIML     84
12     113    Mohit    ECE     38
13     114     Riya     ME     74
14     115    Arjun     CE     90
15     116    Kavya    CSE     77
16     117   Nikhil   AIML     83
17     118     Isha    ECE     58
18     119   Manish     ME     97
19     120    Tanya     CE     62
20     121   Deepak    CSE     48
21     122    Meera   AIML     79
22     123  Saurabh    ECE     86
23     124    Divya     ME     55
24     125    Akash     CE     93
25     126   Bhavna    CSE     41
26     127    Harsh   AIML     67
27     128    Nisha    ECE     82
28     129     Yash     ME     35
29     130    Aditi     CE     89

In [4]:
print(df.head())

   RollNo   Name Branch  Marks
0     101  Aarav    CSE     85
1     102  Priya   AIML     92
2     103  Rahul    ECE     78
3     104  Sneha     ME     65
4     105  Karan     CE     88

In [5]:
print(df.tail())

    RollNo    Name Branch  Marks
25     126  Bhavna    CSE     41
26     127   Harsh   AIML     67
27     128   Nisha    ECE     82
28     129    Yash     ME     35
29     130   Aditi     CE     89

In [ ]:
# Series Operations
# Q-2: Create a pandas series containing the marks of 10 students 
#    : Find the maximum, minimum, mean, and median marks.
marks = pd.Series([85,92,78,65,88,95,56,72,81,69])
print("Student Marks")
print(marks)

Student Marks
0    85
1    92
2    78
3    65
4    88
5    95
6    56
7    72
8    81
9    69
dtype: int64

In [7]:
print("\nMaximum Marks:", marks.max())

Maximum Marks: 95

In [8]:
print("Minimum Marks:", marks.min())

Minimum Marks: 56

In [9]:
print("Mean Marks:", marks.mean())

Mean Marks: 78.1

In [10]:
print("Median Marks:", marks.median())

Median Marks: 79.5

In [ ]:
# DataFrame Information
# Q-3: Create a DataFrame with employee details.
#    : Display its shape, columns, data types, and statistical summary.
employee = {
    "EmpID": [1,2,3,4,5,6,7,8,9,10],
    "Name": ["Amit","Neha","Rohit","Priya","Karan","Simran","Ankit","Pooja","Vivek","Isha"],
    "Department": ["IT","HR","Sales","IT","Finance","HR","IT","Sales","Finance","IT"],
    "Salary": [60000,48000,72000,55000,65000,47000,81000,51000,76000,43000],
    "Experience": [6,4,8,5,7,3,9,5,10,2]
}

df = pd.DataFrame(employee)
df

   EmpID    Name Department  Salary  Experience
0      1    Amit         IT   60000           6
1      2    Neha         HR   48000           4
2      3   Rohit      Sales   72000           8
3      4   Priya         IT   55000           5
4      5   Karan    Finance   65000           7
5      6  Simran         HR   47000           3
6      7   Ankit         IT   81000           9
7      8   Pooja      Sales   51000           5
8      9   Vivek    Finance   76000          10
9     10    Isha         IT   43000           2

In [12]:
print(df.shape)

(10, 5)

In [13]:
print(df.columns)

Index(['EmpID', 'Name', 'Department', 'Salary', 'Experience'], dtype='str')

In [14]:
print(df.dtypes)

EmpID         int64
Name            str
Department      str
Salary        int64
Experience    int64
dtype: object

In [15]:
print(df.describe())

          EmpID        Salary  Experience
count  10.00000     10.000000   10.000000
mean    5.50000  59800.000000    5.900000
std     3.02765  13222.875801    2.601282
min     1.00000  43000.000000    2.000000
25%     3.25000  48750.000000    4.250000
50%     5.50000  57500.000000    5.500000
75%     7.75000  70250.000000    7.750000
max    10.00000  81000.000000   10.000000

In [ ]:
# Selecting Columns
# Q-4: Given a student DataFrame, select only Name, Branch, and Marks columns.
student = {
    "RollNo":[101,102,103,104,105],
    "Name":["Aarav","Priya","Rahul","Sneha","Karan"],
    "Branch":["CSE","AIML","ECE","ME","CE"],
    "Marks":[85,92,78,65,88]
}

df = pd.DataFrame(student)

In [17]:
print(df[["Name","Branch","Marks"]])

    Name Branch  Marks
0  Aarav    CSE     85
1  Priya   AIML     92
2  Rahul    ECE     78
3  Sneha     ME     65
4  Karan     CE     88

In [ ]:
# Selecting Rows
# Q-5: Extract the first 10 rows and rows from index 5 to 15 using iloc.
student = {
    "RollNo": [101,102,103,104,105,106,107,108,109,110,
               111,112,113,114,115,116,117,118,119,120,
               121,122,123,124,125,126,127,128,129,130],

    "Name": ["Aarav","Priya","Rahul","Sneha","Karan",
             "Ananya","Vivek","Neha","Rohit","Simran",
             "Aditya","Pooja","Mohit","Riya","Arjun",
             "Kavya","Nikhil","Isha","Manish","Tanya",
             "Deepak","Meera","Saurabh","Divya","Akash",
             "Bhavna","Harsh","Nisha","Yash","Aditi"],

    "Branch": ["CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE",
               "CSE","AIML","ECE","ME","CE"],

    "Marks": [85,92,78,65,88,
              95,56,72,81,69,
              91,84,38,74,90,
              77,83,58,97,62,
              48,79,86,55,93,
              41,67,82,35,89]
}

df = pd.DataFrame(student)

In [19]:
print(df.iloc[:10])

   RollNo    Name Branch  Marks
0     101   Aarav    CSE     85
1     102   Priya   AIML     92
2     103   Rahul    ECE     78
3     104   Sneha     ME     65
4     105   Karan     CE     88
5     106  Ananya    CSE     95
6     107   Vivek   AIML     56
7     108    Neha    ECE     72
8     109   Rohit     ME     81
9     110  Simran     CE     69

In [20]:
print(df.iloc[5:16])

    RollNo    Name Branch  Marks
5      106  Ananya    CSE     95
6      107   Vivek   AIML     56
7      108    Neha    ECE     72
8      109   Rohit     ME     81
9      110  Simran     CE     69
10     111  Aditya    CSE     91
11     112   Pooja   AIML     84
12     113   Mohit    ECE     38
13     114    Riya     ME     74
14     115   Arjun     CE     90
15     116   Kavya    CSE     77

In [ ]:
# Using loc
# Q-6: Set the student roll number as the index.
#    : Select students with specific roll numbers using loc.
df_indexed = df.set_index('RollNo')
df_indexed

           Name Branch  Marks
RollNo
101       Aarav    CSE     85
102       Priya   AIML     92
103       Rahul    ECE     78
104       Sneha     ME     65
105       Karan     CE     88
106      Ananya    CSE     95
107       Vivek   AIML     56
108        Neha    ECE     72
109       Rohit     ME     81
110      Simran     CE     69
111      Aditya    CSE     91
112       Pooja   AIML     84
113       Mohit    ECE     38
114        Riya     ME     74
115       Arjun     CE     90
116       Kavya    CSE     77
117      Nikhil   AIML     83
118        Isha    ECE     58
119      Manish     ME     97
120       Tanya     CE     62
121      Deepak    CSE     48
122       Meera   AIML     79
123     Saurabh    ECE     86
124       Divya     ME     55
125       Akash     CE     93
126      Bhavna    CSE     41
127       Harsh   AIML     67
128       Nisha    ECE     82
129        Yash     ME     35
130       Aditi     CE     89

In [22]:
# loc  VS iloc 
# loc > include stop boundary in slicing ,jo index par likha hai yeh wahi dhoondhta hai,Label-Based Selection
# iloc > Integer Position-Based Selection, Row/Column Index Numbers (0, 1, 2...),exclude stop boundary in slicing

In [23]:
selected_students = df_indexed.loc[[101,103,105]]
print(selected_students )

         Name Branch  Marks
RollNo
101     Aarav    CSE     85
103     Rahul    ECE     78
105     Karan     CE     88

In [ ]:
# Filtering Data
# Q-7:  Find all students who scored more than 75 marks.
df[df['Marks']>75]

    RollNo     Name Branch  Marks
0      101    Aarav    CSE     85
1      102    Priya   AIML     92
2      103    Rahul    ECE     78
4      105    Karan     CE     88
5      106   Ananya    CSE     95
8      109    Rohit     ME     81
10     111   Aditya    CSE     91
11     112    Pooja   AIML     84
14     115    Arjun     CE     90
15     116    Kavya    CSE     77
16     117   Nikhil   AIML     83
18     119   Manish     ME     97
21     122    Meera   AIML     79
22     123  Saurabh    ECE     86
24     125    Akash     CE     93
27     128    Nisha    ECE     82
29     130    Aditi     CE     89

In [ ]:
# Multiple Conditions
# Q-8: Find students from the CSE branch who scored more than 80.
cse_topper = df[(df['Branch'] == "CSE") & (df['Marks'] > 80)]
print(cse_topper)

    RollNo    Name Branch  Marks
0      101   Aarav    CSE     85
5      106  Ananya    CSE     95
10     111  Aditya    CSE     91

In [ ]:
# Adding a Column
# Q-9: Add a Result column based on marks:
# Marks ≥ 40 → Pass
# Marks < 40 → Fail
# df['result'] = df['Marks'].apply(lambda x:'Pass' if x>= 40 else 'Fail') # Alternative using numpy 
def check_result(marks):
    if marks>40:
        return("Pass")
    else:
        return("Fail")
df['result'] =  df['Marks'].apply(check_result)
print(df)

    RollNo     Name Branch  Marks result
0      101    Aarav    CSE     85   Pass
1      102    Priya   AIML     92   Pass
2      103    Rahul    ECE     78   Pass
3      104    Sneha     ME     65   Pass
4      105    Karan     CE     88   Pass
5      106   Ananya    CSE     95   Pass
6      107    Vivek   AIML     56   Pass
7      108     Neha    ECE     72   Pass
8      109    Rohit     ME     81   Pass
9      110   Simran     CE     69   Pass
10     111   Aditya    CSE     91   Pass
11     112    Pooja   AIML     84   Pass
12     113    Mohit    ECE     38   Fail
13     114     Riya     ME     74   Pass
14     115    Arjun     CE     90   Pass
15     116    Kavya    CSE     77   Pass
16     117   Nikhil   AIML     83   Pass
17     118     Isha    ECE     58   Pass
18     119   Manish     ME     97   Pass
19     120    Tanya     CE     62   Pass
20     121   Deepak    CSE     48   Pass
21     122    Meera   AIML     79   Pass
22     123  Saurabh    ECE     86   Pass
23     124    Divya     ME     55   Pass
24     125    Akash     CE     93   Pass
25     126   Bhavna    CSE     41   Pass
26     127    Harsh   AIML     67   Pass
27     128    Nisha    ECE     82   Pass
28     129     Yash     ME     35   Fail
29     130    Aditi     CE     89   Pass

In [ ]:
# Sorting Data
# Q-10: Sort students by marks in descending order.
# Display the top 5 students.
df_sorted = df.sort_values(by = 'Marks',ascending=False)
top_5 = df_sorted.head(5)
print(top_5)

    RollNo    Name Branch  Marks result
18     119  Manish     ME     97   Pass
5      106  Ananya    CSE     95   Pass
24     125   Akash     CE     93   Pass
1      102   Priya   AIML     92   Pass
10     111  Aditya    CSE     91   Pass

In [28]:
df = pd.read_csv('covid_vaccine_statewise.csv')

In [ ]:
# Missing Values
# Q-11: Create a DataFrame containing missing values.
# Identify missing values using isnull() and isna().
print(df.isnull().sum()) #isnull and isna both are same

Updated On                                0
State                                     0
Total Doses Administered                224
Sessions                                224
 Sites                                  224
First Dose Administered                 224
Second Dose Administered                224
Male (Doses Administered)               384
Female (Doses Administered)             384
Transgender (Doses Administered)        384
 Covaxin (Doses Administered)           224
CoviShield (Doses Administered)         224
Sputnik V (Doses Administered)         4850
AEFI                                   2407
18-44 Years (Doses Administered)       6143
45-60 Years (Doses Administered)       6143
60+ Years (Doses Administered)         6143
18-44 Years(Individuals Vaccinated)    4112
45-60 Years(Individuals Vaccinated)    4111
60+ Years(Individuals Vaccinated)      4111
Male(Individuals Vaccinated)           7685
Female(Individuals Vaccinated)         7685
Transgender(Individuals Vaccinated)    7685
Total Individuals Vaccinated           1926
dtype: int64

In [ ]:
# Q-12: Handling Missing Values
# Replace missing numerical values with the column mean.
# Replace missing numerical values with mean
num_cols = df.select_dtypes(include = ['float64','int64']).columns #select those columns whose dtpes = int and float
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())
print(df[num_cols].isna().sum())

Total Doses Administered               0
Sessions                               0
 Sites                                 0
First Dose Administered                0
Second Dose Administered               0
Male (Doses Administered)              0
Female (Doses Administered)            0
Transgender (Doses Administered)       0
 Covaxin (Doses Administered)          0
CoviShield (Doses Administered)        0
Sputnik V (Doses Administered)         0
AEFI                                   0
18-44 Years (Doses Administered)       0
45-60 Years (Doses Administered)       0
60+ Years (Doses Administered)         0
18-44 Years(Individuals Vaccinated)    0
45-60 Years(Individuals Vaccinated)    0
60+ Years(Individuals Vaccinated)      0
Male(Individuals Vaccinated)           0
Female(Individuals Vaccinated)         0
Transgender(Individuals Vaccinated)    0
Total Individuals Vaccinated           0
dtype: int64

In [ ]:
data = {
    'RollNo': [101, 102, 102, 103, 104, 104, 104],
    'Student_Name': ['Aarav', 'Priya', 'Priya', 'Rahul', 'Sneha', 'Sneha', 'Sneha'],
    'Branch': ['CSE', 'AIML', 'AIML', 'ECE', 'ME', 'ME', 'ME'],
    'Student_Marks': [85, 92, 92, 78, 65, 65, 65]
}
# Removing Duplicates
# Q-13: Create a DataFrame containing duplicate student records.
# Remove duplicate rows.
df = pd.DataFrame(data)
print(df.duplicated().sum())
df_cleaned = df.drop_duplicates()
print(df_cleaned.duplicated().sum())

3

In [ ]:
# Rename Columns
# Q-14: Rename Student_Name to Name and Student_Marks to Marks.
df = df.rename({
    'Student_Name' : 'Name',
    'Student_Marks':'Marks'
})
df

   RollNo Student_Name Branch  Student_Marks
0     101        Aarav    CSE             85
1     102        Priya   AIML             92
2     102        Priya   AIML             92
3     103        Rahul    ECE             78
4     104        Sneha     ME             65
5     104        Sneha     ME             65
6     104        Sneha     ME             65

In [ ]:
# Export and Import
# Q-15: Save a DataFrame as a CSV file.
# Q-16: Read the CSV file back into Pandas.
df.to_csv('students.csv',index=False)

In [35]:
pd.read_csv('students.csv')

   RollNo Student_Name Branch  Student_Marks
0     101        Aarav    CSE             85
1     102        Priya   AIML             92
2     102        Priya   AIML             92
3     103        Rahul    ECE             78
4     104        Sneha     ME             65
5     104        Sneha     ME             65
6     104        Sneha     ME             65

In [ ]:
# GroupBy – Average Marks
# Q-17: Given student data containing Branch and Marks, calculate the average marks for each branch.
avg_marks = df.groupby('Branch')['Student_Marks'].mean().reset_index() #reset_index to get the data in normal datafram format
print(avg_marks)

  Branch  Student_Marks
0   AIML           92.0
1    CSE           85.0
2    ECE           78.0
3     ME           65.0

In [ ]:
# GroupBy – Multiple Aggregations
# Q-18: Find the minimum, maximum, average, and standard deviation of marks for each branch.
branch_stats = df.groupby('Branch')['Student_Marks'].agg(['min','max','mean','std']).reset_index()
print(branch_stats)

  Branch  min  max  mean  std
0   AIML   92   92  92.0  0.0
1    CSE   85   85  85.0  NaN
2    ECE   78   78  78.0  NaN
3     ME   65   65  65.0  0.0

In [ ]:
# Value Counts
# Q-19: Given a dataset of student branches, count the number of students in each branch.
branch_counts = df['Branch'].value_counts()

print(branch_counts)

Branch
ME      3
AIML    2
CSE     1
ECE     1
Name: count, dtype: int64

In [ ]:
# Conditional Column
# Q-20: Create a Grade column based on the Marks column.
# A: ≥ 90
# B: 75–89
# C: 60–74
# D: 40–59
# F: < 40
def assign_grade(marks):
    if marks >= 90:
        return 'A'
    elif marks >= 75:
        return 'B'
    elif marks >= 60:
        return 'C'
    elif marks >= 40:
        return 'D'
    else:
        return 'F'
df['Grade'] = df['Student_Marks'].apply(assign_grade)
print(df)

   RollNo Student_Name Branch  Student_Marks Grade
0     101        Aarav    CSE             85     B
1     102        Priya   AIML             92     A
2     102        Priya   AIML             92     A
3     103        Rahul    ECE             78     B
4     104        Sneha     ME             65     C
5     104        Sneha     ME             65     C
6     104        Sneha     ME             65     C

In [ ]:
# Apply Function
# Q-21: Use the apply() function to calculate the percentage of students based on marks obtained out of 100.
data = {
    'Name': ['Aarav', 'Priya', 'rahul', 'Sneha', 'Karan'],
    'Marks_Obtained': [425, 390, 310, 240, 180]
}
df = pd.DataFrame(data)
def calc_per(Marks):
    return (Marks/500)*100
df['Percentage'] = df['Marks_Obtained'].apply(calc_per)
print(df)

    Name  Marks_Obtained  Percentage
0  Aarav             425        85.0
1  Priya             390        78.0
2  rahul             310        62.0
3  Sneha             240        48.0
4  Karan             180        36.0

In [ ]:
# String Operations
# Q-22: Given student names, convert all names to uppercase.
df['Name_upper'] = df['Name'].str.upper()
print(df)

    Name  Marks_Obtained  Percentage Name_upper
0  Aarav             425        85.0      AARAV
1  Priya             390        78.0      PRIYA
2  rahul             310        62.0      RAHUL
3  Sneha             240        48.0      SNEHA
4  Karan             180        36.0      KARAN

In [ ]:
# Q-23: Extract the first letter of each name.
df['first_letter'] = df['Name'].str[0]
print(df)

    Name  Marks_Obtained  Percentage Name_upper first_letter
0  Aarav             425        85.0      AARAV            A
1  Priya             390        78.0      PRIYA            P
2  rahul             310        62.0      RAHUL            r
3  Sneha             240        48.0      SNEHA            S
4  Karan             180        36.0      KARAN            K

In [ ]:
# DateTime Operations
# Q-24: Create a DataFrame containing employee joining dates.
# Q-25: Extract year, month, and day from the joining date.
df_emp = pd.read_csv('employee_data.csv')

# Convert Joining_Date to datetime format
df_emp['Joining_Date'] = pd.to_datetime(df_emp['Joining_Date'])

In [47]:
df_emp['Year'] = df_emp['Joining_Date'].dt.year
df_emp['Month'] = df_emp['Joining_Date'].dt.month
df_emp['Day'] = df_emp['Joining_Date'].dt.day
print(df_emp[['Name', 'Joining_Date', 'Year', 'Month', 'Day']].head())

           Name Joining_Date  Year  Month  Day
0  Aarav Sharma   2018-03-15  2018      3   15
1   Priya Patel   2019-06-20  2019      6   20
2   Rahul Verma   2015-01-10  2015      1   10
3   Sneha Gupta   2021-11-05  2021     11    5
4   Karan Singh   2017-08-12  2017      8   12