#  BASIC PANDAS EXERCISE

What is Pandas?
pandas is an open-source data analysis and manipulation library for Python. It provides data structures like Series and DataFrame that make it easy to work with structured data, perform data cleaning, transformation, and analysis.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

#  1. Create a DataFrame

In [2]:
# Q Create a DataFrame containing student names, roll numbers, branch, and marks.
student_data = {
    'Student Name': ['Aarav', 'Ananya', 'Diya', 'Ishaan', 'Kabir', 'Meera', 'Rahul', 'Riya',  'Arjun', 'Saanvi'],
    'Roll Number': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Branch': ['CSE', 'ECE', 'ME', 'CSE', 'IT', 'CE', 'CSE', 'ECE', 'IT', 'ME'],
    'Marks': [85, 92, 78, 65, 88, 74, 91, 83, 79, 81]
}

df = pd.DataFrame(student_data)

In [3]:
# Q Display the first 5 and last 5 records.
print(df.head())
print(df.tail())

  Student Name  Roll Number Branch  Marks
0        Aarav          101    CSE     85
1       Ananya          102    ECE     92
2         Diya          103     ME     78
3       Ishaan          104    CSE     65
4        Kabir          105     IT     88
  Student Name  Roll Number Branch  Marks
5        Meera          106     CE     74
6        Rahul          107    CSE     91
7         Riya          108    ECE     83
8        Arjun          109     IT     79
9       Saanvi          110     ME     81

# 2. Series Operations

In [5]:
# Q o	Create a Pandas Series containing marks of 10 students.
marks = student_data["Marks"]
Sname = student_data['Student Name']
S = pd.Series(marks , index= Sname)
S

Aarav     85
Ananya    92
Diya      78
Ishaan    65
Kabir     88
Meera     74
Rahul     91
Riya      83
Arjun     79
Saanvi    81
dtype: int64

In [6]:
print("Max : ", S.max())
print("Min : ",S.min())
print("Mean : ",S.mean())
print("Median : ",S.median())

Max :  92
Min :  65
Mean :  81.6
Median :  82.0

# 3. DataFrame Information

In [7]:
employee_data = {
    'Employee ID':[101, 102, 103, 104, 105, 106, 107, 108],
    'Name': ['Amit', 'Priya', 'Vikram', 'Neha', 'Rohan', 'Sneha', 'Aditya', 'Pooja'],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing', 'Finance', 'HR', 'IT'],
    'Salary': [85000, 60000, 95000, 87000, 55000, 92000, 62000, 89000]
}
df_e = pd.DataFrame(employee_data)

In [9]:
# o	Display its shape, columns, data types, and statistical summary.
print(df_e.shape)
print(df_e.columns)
print(df_e.dtypes)
df_e["Salary"].describe()

(8, 4)
Index(['Employee ID', 'Name', 'Department', 'Salary'], dtype='str')
Employee ID    int64
Name             str
Department       str
Salary         int64
dtype: object

count        8.000000
mean     78125.000000
std      16234.333107
min      55000.000000
25%      61500.000000
50%      86000.000000
75%      89750.000000
max      95000.000000
Name: Salary, dtype: float64

# 4. Selecting Columns

In [12]:
# o	Given a student DataFrame, select only Name, Branch, and Marks columns.
df[["Student Name" , "Branch" , "Marks"]].head()

  Student Name Branch  Marks
0        Aarav    CSE     85
1       Ananya    ECE     92
2         Diya     ME     78
3       Ishaan    CSE     65
4        Kabir     IT     88

# 5. Selecting Rows

In [13]:
df_e.iloc[5:16]

   Employee ID    Name Department  Salary
5          106   Sneha    Finance   92000
6          107  Aditya         HR   62000
7          108   Pooja         IT   89000

# 6. Using loc

In [14]:
## o	Set the student roll number as the index.
# df["Roll Number"]
df.set_index(keys="Roll Number", inplace=True)

In [15]:
# o	Select students with specific roll numbers using loc.
df.loc[[102,105]]

            Student Name Branch  Marks
Roll Number
102               Ananya    ECE     92
105                Kabir     IT     88

# 7. Filtering Data

In [16]:
#o	Find all students who scored more than 75 marks.
df[df["Marks"] >= 75]

            Student Name Branch  Marks
Roll Number
101                Aarav    CSE     85
102               Ananya    ECE     92
103                 Diya     ME     78
105                Kabir     IT     88
107                Rahul    CSE     91
108                 Riya    ECE     83
109                Arjun     IT     79
110               Saanvi     ME     81

# 8. Multiple Conditions

In [17]:
# o	Find students from the CSE branch who scored more than 80.
df[(df["Marks"]  >= 80)  & (  df["Branch"] == "CSE")]

            Student Name Branch  Marks
Roll Number
101                Aarav    CSE     85
107                Rahul    CSE     91

# 9. Adding a Column

In [18]:
## o	Add a Result column based on marks:
# 	Marks ≥ 40 → Pass
# 	Marks < 40 → Fail

df["Result"] = np.where(df["Marks"] >= 40, "Pass", "Fail")
df.head()

            Student Name Branch  Marks Result
Roll Number
101                Aarav    CSE     85   Pass
102               Ananya    ECE     92   Pass
103                 Diya     ME     78   Pass
104               Ishaan    CSE     65   Pass
105                Kabir     IT     88   Pass

# 10. Sorting Data

In [19]:
## o	Sort students by marks in descending order.
df_top = df.sort_values(by = "Marks" ,ascending = False)
df_top

            Student Name Branch  Marks Result
Roll Number
102               Ananya    ECE     92   Pass
107                Rahul    CSE     91   Pass
105                Kabir     IT     88   Pass
101                Aarav    CSE     85   Pass
108                 Riya    ECE     83   Pass
110               Saanvi     ME     81   Pass
109                Arjun     IT     79   Pass
103                 Diya     ME     78   Pass
106                Meera     CE     74   Pass
104               Ishaan    CSE     65   Pass

In [20]:
## o	Display the top 5 students.
df_top.head()

            Student Name Branch  Marks Result
Roll Number
102               Ananya    ECE     92   Pass
107                Rahul    CSE     91   Pass
105                Kabir     IT     88   Pass
101                Aarav    CSE     85   Pass
108                 Riya    ECE     83   Pass

# 11. Missing Values

In [25]:
data = {
    "Roll Number":[101, 102, np.nan, 104, 105, 106, np.nan, 108, 109, 110],
    "Student Name":["Aarav", "Ananya", "Diya", np.nan, "Kabir", "Meera", "Rahul", "Riya", np.nan, "Saanvi"],
    "Branch":["CSE", np.nan, "ME", "CSE", "IT", "CE", np.nan, "ECE", "IT", "ME"],
    "Marks":[85, np.nan, 78, 65, 88, np.nan, 91, 83, 79, 81],}

df_m = pd.DataFrame(data)
df_m

   Roll Number Student Name Branch  Marks
0        101.0        Aarav    CSE   85.0
1        102.0       Ananya    NaN    NaN
2          NaN         Diya     ME   78.0
3        104.0          NaN    CSE   65.0
4        105.0        Kabir     IT   88.0
5        106.0        Meera     CE    NaN
6          NaN        Rahul    NaN   91.0
7        108.0         Riya    ECE   83.0
8        109.0          NaN     IT   79.0
9        110.0       Saanvi     ME   81.0

In [22]:
# o	Identify missing values using isnull() and isna().
df_m.isna().sum()

Roll Number     2
Student Name    2
Branch          2
Marks           2
dtype: int64

# 12. Handling Missing Values

In [24]:
df_m['Marks'] = df_m['Marks'].fillna(df_m['Marks'].mean()) 
df_m

   Roll Number Student Name Branch  Marks
0        101.0        Aarav    CSE  85.00
1        102.0       Ananya    NaN  81.25
2          NaN         Diya     ME  78.00
3        104.0          NaN    CSE  65.00
4        105.0        Kabir     IT  88.00
5        106.0        Meera     CE  81.25
6          NaN        Rahul    NaN  91.00
7        108.0         Riya    ECE  83.00
8        109.0          NaN     IT  79.00
9        110.0       Saanvi     ME  81.00

# 13. Removing Duplicates

In [26]:
dup = pd.DataFrame({
    'Roll_No': [101, 102, 101, 103],
    'Name': ['Rahul', 'Priya', 'Rahul', 'Amit'],
    'Marks': [85, 92, 85, 78]
})
dup

   Roll_No   Name  Marks
0      101  Rahul     85
1      102  Priya     92
2      101  Rahul     85
3      103   Amit     78

In [27]:
dup.drop_duplicates

<bound method DataFrame.drop_duplicates of    Roll_No   Name  Marks
0      101  Rahul     85
1      102  Priya     92
2      101  Rahul     85
3      103   Amit     78>

# 14. Rename Columns

In [29]:
# o	Rename Student_Name to Name and Student_Marks to Marks.
df_students = df.reset_index().rename(columns={
    "Student Name": "Student_Name",
    "Marks": "Student_Marks"
})
df_students

   Roll Number Student_Name Branch  Student_Marks Result
0          101        Aarav    CSE             85   Pass
1          102       Ananya    ECE             92   Pass
2          103         Diya     ME             78   Pass
3          104       Ishaan    CSE             65   Pass
4          105        Kabir     IT             88   Pass
5          106        Meera     CE             74   Pass
6          107        Rahul    CSE             91   Pass
7          108         Riya    ECE             83   Pass
8          109        Arjun     IT             79   Pass
9          110       Saanvi     ME             81   Pass